package main

import (
	"database/sql"
	"log"
	"net/http"
	"os"

	"github.com/go-chi/chi"
	"github.com/go-chi/cors"
	"github.com/joho/godotenv"

	"github.com/omkarkhot0500/rssagg/internal/database"

	_ "github.com/lib/pq"
)

// apiConfig is a struct that holds shared things we want
// to use across handlers (right now only the database connection)
type apiConfig struct {
	DB *database.Queries
}

func main() {

	// Load environment variables from .env file into the program
	// so we can access them using os.Getenv
	godotenv.Load(".env")

	// Read the PORT value from environment variables
	port := os.Getenv("PORT")
	if port == "" {
		log.Fatal("PORT environment variable is not set")
	}

	// Read database connection string from .env
	dbURL := os.Getenv("DATABASE_URL")
	if dbURL == "" {
		log.Fatal("DATABASE_URL environment variable is not set")
	}

	// Open connection to PostgreSQL database
	// this does not actually query yet, just prepares the connection
	db, err := sql.Open("postgres", dbURL)
	if err != nil {
		log.Fatal(err)
	}

	// Create database query helper generated by sqlc
	// this lets us call functions like CreateUser instead of writing SQL manually
	dbQueries := database.New(db)

	// Create config object and store DB inside it
	// we pass this config into handlers so they can use the DB
	apiCfg := apiConfig{
		DB: dbQueries,
	}

	// Create a new router using chi
	router := chi.NewRouter()

	// Add CORS middleware
	// this allows frontend apps to call this backend API
	router.Use(cors.Handler(cors.Options{
		AllowedOrigins:   []string{"https://*", "http://*"},
		AllowedMethods:   []string{"GET", "POST", "PUT", "DELETE", "OPTIONS"},
		AllowedHeaders:   []string{"*"},
		ExposedHeaders:   []string{"Link"},
		AllowCredentials: false,
		MaxAge:           300,
	}))

	// Create versioned router for API v1
	v1Router := chi.NewRouter()

	// POST /v1/users → create a new user
	// calls handlerUsersCreate function
	v1Router.Post("/users", apiCfg.handlerUsersCreate)

	v1Router.Post("/feeds", apiCfg.middlewareAuth(apiCfg.handlerFeedCreate))

	// GET /v1/users → get user info based on API key
	// calls handlerUsersGet function
	v1Router.Get("/users", apiCfg.middlewareAuth(apiCfg.handlerUsersGet))

	// Health check route to see if server is running
	v1Router.Get("/healthz", handlerReadiness)

	// Route that intentionally returns an error (for testing)
	v1Router.Get("/err", handlerErr)

	// Mount v1 routes under /v1 path
	router.Mount("/v1", v1Router)

	// Create HTTP server with port and router
	srv := &http.Server{
		Addr:    ":" + port,
		Handler: router,
	}

	// Print message that server started
	log.Printf("Serving on port: %s\n", port)

	// Start server and stop program if it crashes
	log.Fatal(srv.ListenAndServe())
}
